### ISSUE TITLE
aPDU/nPDU value are not reported as part of the message type 0x8000 and 0x8011

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGatev2#12]
The aPDU/nPDU remains to 0 when receiving the 0x8000 or 0x8011 messages .

Is that a regression from the V1 firmware are is the new stack behave differently ?

**Comment by fairecasoimeme** [comment]
fixed on v320
https://github.com/fairecasoimeme/ZiGatev2/commit/e44b96eb27b22db25b719cf8d7e667d681e7a5de

**Comment by pipiche38** [comment]
https://github.com/fairecasoimeme/ZiGatev2/releases/tag/v3.20
