### ISSUE TITLE
Release tag broken ?

### ISSUE THREAD

**Issue by tobozo** [fairecasoimeme/ZiGatev2#22]
Hi,

For some reason, clicking on the tag link in the release page of this repository generates a broken tree in the UI.

![image](https://user-images.githubusercontent.com/1893754/131990737-03b13ae1-dfbb-42d0-9091-b750db56aa7c.png)

https://github.com/fairecasoimeme/ZiGatev2/tree/refs/tags/v3.20 => generated **files and folders links** lead to 404 page

Moreover, the tag is missing from the tree widget name.

![image](https://user-images.githubusercontent.com/1893754/132001277-43ab9115-1fb1-49b4-97ff-23679563235b.png)

Obviously removing "/refs/tags/" from the URL fixes the symptoms but why does github UI produce such invalid links in the first place is beyond me :thinking: 

I have a few repositories affected with the same strange issue, can't figure out if it's a repo problem, a browser problem, or maybe a locale (French) problem, however this is beginning to produce symptoms outside github, in remote registries.

I understand this issue is not directly related to this project, so feel free to just close it if you don't have time/energy for that.

**Comment by pipiche38** [comment]
works for me !

<img width="1399" alt="Screenshot 2021-09-03 at 13 12 26" src="https://user-images.githubusercontent.com/8291674/131996571-35478d40-4a02-4050-9fad-e7a09dc2c278.png">

**Comment by tobozo** [comment]
even when you click on one of the files or folders ?

**Comment by pipiche38** [comment]
indeed when clicking it doesn't!

**Comment by tobozo** [comment]
Thanks, that means I'm not hallucinating :disappointed_relieved: 

I've created a ticket on github support platform for that, and linked to my affected repositores along with this one, will post the followup here.

**Comment by tobozo** [comment]
update !

got a reply from github support, with confirmation that it seems to happen when a release is created with **a tag name that's similar to an existing branch name**. 

Release tag links in such cases seem to generate trees with broken blobs links.

There's no ETA for a fix, meanwhile it is recommended to prefix tag names with a `v` (e.g. `v1.0.0`) when the branch has a similar name.

**Comment by fairecasoimeme** [comment]
Hi,
Ho thank you for the tips !
I won't make the same mistake again
Fred
