### ISSUE TITLE
Time to time not able to pair any more device

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGatev2#24]
Time to time, the ZiGate seems to be in a frozen mode and cannot accept any more pairing.

after a while , then the pairing is back and possible

**Comment by fairecasoimeme** [comment]
could you say more ? led blinking ? other command passed or nothing ? 
the goal is to know where I have to search.

**Comment by pipiche38** [comment]
Yes, the ZiGate is blinking.
We see in the sniff the PermitToJoing message with 255 as duration, broadcasted.
then the beacons from the device which is looking to enter in the network

nothing else. No association for instance

**Comment by jmaury** [comment]
I've got the same problem : the ZiGate is blinking but I can't pair any device anymore.
On my side after 3 days I still can't pair.
All devices already paired seem to work well.

When I flash the ZiGate (with erase option) then I can pair the device that I can't before.

**Comment by jmaury** [comment]
I tried with new firmware 3.21. The problem is still there.
I'm back on ZiGate V1 with 3.20 OPDM firmware and everything is working fine.
How can I help ?

**Comment by JoachimCanu** [comment]
J'ai le même problème.
J'essai d'ajouter de nouveaux appareils mais rien ne se passe. Aucun log.

**Comment by fairecasoimeme** [comment]
when this occurs, could you do a save with this tutorial : https://zigate.fr/documentation/sauvegardez-et-restaurez-votre-zigate-v2/
And send to me by email : contact@zigate.fr

Thx in advance

**Comment by mickadam29** [comment]
I have the same problem. I try to add new devices but nothing happens. No log. Example device with problem : Ikea Tradfri E1743. 
Exactly same as describe by @pipiche38  on 23/10 
Zigate+ 3.21
Works fine with Pizigate 3.20
