### ISSUE TITLE
Integrate and support new Aqara Door Sensor MCCGQ14LM

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGatev2#29]
It looks like the new Aqara Door Sensor ( MCCGQ14LM ) does a Node Descriptor toward ZiGate and in that case the ZiGate (Controleur) MUST answer with Xiaomi manufacturer code.

Please do implement such feature as it has been done by the other GW ( z2m, deConz ) so Zigate can support that model

CC: dresden-elektronik/deconz-rest-plugin#5403 (comment)
https://github.com/fairecasoimeme/ZiGate/issues/381

**Comment by pipiche38** [comment]
Here is what have been done for z2m and there is a similar one for deConz
https://github.com/Koenkk/Z-Stack-firmware/blob/f29b4525bb7bfdc28c91139d0926469bb5754ab9/coordinator/Z-Stack_3.x.0/firmware.patch#L533

**Comment by fairecasoimeme** [comment]
I will add an API command to customize manufacturer code.
Do you think that's would be enough ?

**Comment by pipiche38** [comment]
https://github.com/fairecasoimeme/ZiGate/issues/381

**Comment by pipiche38** [comment]
> I will add an API command to customize manufacturer code. Do you think that's would be enough ?

I think this should be implemented (hard) in the firmware, based on the MAC ADDRESS range , then we position the manufacturer ID. At least for the Xiaomi and Lumi .

**Comment by pipiche38** [comment]
Having an API , wouldn't help , otherwise this has to be setup at startup, as the node descriptor is requested usally by the device, just after the device annoucement

**Comment by fairecasoimeme** [comment]
So OK, I wanted to do something more open but I understand. I'm going to do the same hard fix than deconz patch. 
Thanks for contributions

**Comment by pipiche38** [comment]
Don't think we need anything fancy here, but as you wish

**Comment by fairecasoimeme** [comment]
fixed on v3.21
