### ISSUE TITLE
Probleme d'acces en pizigate

### ISSUE THREAD

**Issue by landaisbenj** [fairecasoimeme/ZiGatev2#34]
Bonjour.

J'ai installé le module pizigate sur mon raspberry pi. Je comptai l'utiliser avec Home assistant, j'ai donc transformer le raspberry en passerelle avec socat comme indiqué dans la doc.

1. Installation du zigate,
2. Configuration du raspberry pi,
3. Test avec le pizigate tool (tout est ok),
4. Installation de socat, que j'arrive à lancer, mais je ne sais pas le tester. Tout ce que j'ai fais, c'est demarrer socat, ouvrir l'url avec le port 9999 et je vois bien des lignes apparaitre sur socat (sauf que je ne sais pas troobleshooter....). Au bout d'un moment socat se ferme tout seul. 
5. J'ai donc aussi configuré le service systemctl, puis apres redemarrage du PI, la led bleu s'allume tout seul.

Seulement quand je l'ajoute à Home assistant, j'ai un message d'erreur. La passerelle à l'air introuvable :

```
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.0.172', 9999)
```

Mon probleme c'est que je ne sais pas vérifier si tout ce que j'ai fais sur le raspberry fonctionne... Vous auriez une idée ?

**Comment by landaisbenj** [comment]
Pour info, afin de reduire le champs de recherche, j'ai installé un home assistant sur le raspberry. Lorsque je lance l'integration zha, il me trouve bien un device, mais j'ai toujours une erreur.

**Comment by fairecasoimeme** [comment]
Bonjour,
Avant de passer sur ZHA, pouvez vous suivre ce tutoriel ?
https://zigate.fr/documentation/tester-le-module-wifi/

Fred

**Comment by landaisbenj** [comment]
Ok. Je dois finir le test que j'avais commencé, c'est à dire installation de HAOS sur le pi car hier c'etait HA container, donc pas sur que je sois capable de réaliser le bon mappage... En parrallele, j'avais voulu testé une mise à jour de la distri, et je me suis rendu compte que j'etais incapable d'installer wiringpi car detrécié... 

Je test tout ca et je reviens vers vous.

**Comment by landaisbenj** [comment]
Voila ce que j'ai fais : 

1.  Nouvel installation de raspian, donc je repars de zero
2. Paramétrage à yes du remote GPIO via raspi-config (je ne sais pas si c'est pertinent mais bon...)
3. Mise à jour update/upgrade du raspberry
4. Test gpio nok
5. Comme wiringpi est déprécié je l'ai installé via ce repos : https://github.com/WiringPi/WiringPi. 
```
Git clone https://github.com/WiringPi/WiringPi
cd WiringPi
./build...
```

6. Test GPIO OK
7. J'ai passé cette procédure : https://zigate.fr/documentation/parametrer-la-pizigate/
8. Ensuite je me suis rappelé qu'il fallait que j'effectue ces changements : https://zigate.fr/documentation/compatibilite-raspberry-pi-3-et-zero-w/ j'avais deja "enable_uart=1" je suppose que c'est mon action en 2.

J'ai redémarré, j'ai bien la led bleu.

9. Ensuite j'ai passé cette procédure : https://zigate.fr/documentation/tester-sa-pizigate/ depuis le début je n'ai jamais eu d'erreur (a par la difficulté pour wiringpi )
10. Ici j'ai une difficulté : sudo ./PiZiGate_test /dev/ttyAMA0 je ne suis pas capable de savoir si /dev/ttyAMA0 est la bonne adresse ...
voici le resultat : 
```
pi@raspberrypi:~ $ sudo PiZiGate-tools/test/PiZiGate_test /dev/ttyAMA0
RPI Model searching ...
Warning !!! you must modify /boot/config.txt
Verifying /boot/cmdline.txt ...
+ /boot/cmdline.txt seems to be OK
Verifying /boot/config.txt ...
+ /boot/config.txt seems to be OK
Warning !!! if it's not the case, you have to execute the following commands : 
sudo systemctl disable hciuart
sudo usermod -aG gpio pi
then reboot the PI
Searching /dev/ttyAMA0...
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
+ Port : /dev/ttyAMA0 is not used
Verif GPIOs ...
+ GPIO 0 (RESET) --> OK
+ GPIO 2 (FLASH) --> OK
Config GPIOs ...
+ GPIO 0 (RESET) --> OK
+ GPIO 2 (FLASH) --> OK
Opening : /dev/ttyAMA0 ...
+ /dev/ttyAMA0 opened --> OK
+ Packet 01 02 10 10 02 10 02 10 10 03 sent --> OK
+ Packet received --> OK
size : 150
 01 00 03 02 00 02 03 00 00 03 
01 80 24 00 0d c1 01 00 00 00 15 8d 00 05 d2 9a b7 0b 00 03 
01 80 06 00 02 85 01 00 03 
01 80 01 00 22 ce 06 41 50 50 3a 20 4e 4f 54 20 65 6e 74 65 72 69 6e 67 20 41 50 50 5f 76 4e 63 69 53 74 61 72 74 28 29 03 
01 80 00 00 09 99 00 00 00 10 00 00 00 00 00 03 
01 80 10 00 05 b2 00 05 03 21 00 03 
```

Comme je n'en suis pas encore à l'étape socat, je voulais savoir si j'ai pas un premier probleme ici (je précise qu'avec mes derniers tests, je n'avais jamais eu ce message) : 
```
lsof: WARNING: can't stat() fuse.gvfsd-fuse file system /run/user/1000/gvfs
      Output information may be incomplete.
```

**Comment by fairecasoimeme** [comment]
Bonjour,
Pour le moment tout est ok. La pizigate communique

Fred

**Comment by landaisbenj** [comment]
Ok merci pour l'info, bien que ce soit compliqué pour moi de faire comme si il n'y avait pas de message d'attention ^^' 

11. Je continue donc avec cette procédure : https://zigate.fr/documentation/creer-une-zigate-ethernet-avec-un-raspberry-pi/
12. Ici j'ai voulu ajouter l'option -vvv avec le premier test, mais l'option n'a plus l'air disponible sur la documentation... Je passe donc directement au script:
```
#!/bin/sh

gpio mode O out
gpio mode 2 out
gpio write 2 1
gpio write 0 0
gpio write 0 1
/usr/bin/socat /dev/ttyAMA0,b115200,raw,echo=0 tcp4-listen:9999
```
Comme je pense que ca fait doublon avec l'etape /etc/rc.local en 7. je pense que j'irai la retirer plus tard...
13. Je crée le service systemctl et je controle que tout soit ok: 
```
$ systemctl status socat.service
● socat.service - ZiGate_Socat
     Loaded: loaded (/etc/systemd/system/socat.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-02-01 11:51:07 GMT; 6s ago
   Main PID: 17158 (socat_daemon.sh)
      Tasks: 2 (limit: 1597)
        CPU: 33ms
     CGroup: /system.slice/socat.service
             ├─17158 /bin/sh /home/pi/socat_daemon.sh
             └─17164 /usr/bin/socat /dev/ttyAMA0,b115200,raw,echo=0 tcp4-listen:9999

févr. 01 11:51:07 raspberrypi systemd[1]: Started ZiGate_Socat.
```

14. Je passe donc au test et j'ai l'air de bien avoir un retour de fonctionnement...
![image](https://user-images.githubusercontent.com/32144431/151964004-439db3c1-710a-4eca-9f7d-29970fa3acc6.png)

**Comment by landaisbenj** [comment]
Bon vu que tout avait l'air ok, j'ai ajouté l'integration ZHA, et voila que tout fonctionne ... Comme je ne sais pas trop pourquoi, je clos quand meme... (entre temps je suis passé en beta sur home assistant). Je vais pouvoir tester maintenant l'installation du module TIC :D
