### ISSUE TITLE
0005-0321: Message 004D remonte n'importe quoi

### ISSUE THREAD

**Issue by tcharp38** [fairecasoimeme/ZiGatev2#36]
Hello

En creusant un souci utilisateur Abeille, je reste sec.
Le message 004D (dans son cas) semble remonter n'importe quoi, à commencer par l'adresse source.
On peut comparer le 8002 qui precede le 004D.
Evidement l'adresse IEEE est elle aussi n'importe quoi.

Question... le format de ce message à changé en v2 ?

[2022-04-03 15:52:54] Abeille1, Type=8002/Data indication, Status=00, ProfId=0000, ClustId=0013, SrcEP=00, DstEP=00, SrcAddrMode=02, SrcAddr=338E, DstAddrMode=02, DstAddr=0000
[2022-04-03 15:52:54] Handled by decode004D
[2022-04-03 15:52:54] Abeille1, Type=004d/Device announce, Addr=1D0A, ExtAddr=0400536D04015D6B, MACCapa=B4

[2022-04-03 15:57:27] Abeille1, Type=8002/Data indication, Status=00, ProfId=0000, ClustId=0013, SrcEP=00, DstEP=00, SrcAddrMode=02, SrcAddr=338E, DstAddrMode=02, DstAddr=0000
[2022-04-03 15:57:27] Handled by decode004D
[2022-04-03 15:57:27] Abeille1, Type=004d/Device announce, Addr=8D00, ExtAddr=0000001E040048DC, MACCapa=02

[2022-04-03 15:59:28] Abeille1, Type=8002/Data indication, Status=00, ProfId=0000, ClustId=0013, SrcEP=00, DstEP=00, SrcAddrMode=02, SrcAddr=338E, DstAddrMode=02, DstAddr=0000
[2022-04-03 15:59:28] Handled by decode004D
[2022-04-03 15:59:28] Abeille1, Type=004d/Device announce, Addr=1C8E, ExtAddr=0400536D04015D6B, MACCapa=B4

Une idée ?
Merci

Sujet Abeille correspondant: https://github.com/KiwiHC16/Abeille/issues/2368#

**Comment by fairecasoimeme** [comment]
Le format n'a normalement pas changé.
Pourrais-tu envoyer le RAW data pour mieux comprendre et valider si le le format est ok ?

**Comment by tcharp38** [comment]
Voila pour le cas suivant

> [2022-04-03 18:24:05] Abeille1, Type=8002/Data indication, Status=00, ProfId=0000, ClustId=0013, SrcEP=00, DstEP=00, SrcAddrMode=02, SrcAddr=338E, DstAddrMode=02, DstAddr=0000
> [2022-04-03 18:24:05]   Handled by decode004D
> [2022-04-03 18:24:05] Abeille1, Type=004d/Device announce, Addr=21E2, ExtAddr=0400536D04015D6B, MACCapa=B4
> 

La zigate envoi

> [2022-04-03 18:24:05] Got "8002001A490000000013000002338E020000008E33190E1E25004B12008E39"
> [2022-04-03 18:24:05] Got "004D000C0621E20400536D04015D6BB439"

En décodant le 8002 il me semble tout a fait correct. Ca confirme le 004D daubé

> 8002001A490000000013000002338E020000008E33190E1E25004B12008E39
> ... 8002
> ... 001A
> ... 49
> ... ... 00
> ... ... 0000 => profile
> ... ... 0013 => cluster
> ... ... 00
> ... ... 00
> ... ... 02
> ... ... 338E
> ... ... 02
> ... ... 0000
> ... ... ... 00
> ... ... ... 8E33 => addr 338E
> ... ... ... 190E1E25004B1200 => iEEE 00124B00251E0E19
> ... ... ... 8E => capa
> ... ... ... 39

**Comment by fairecasoimeme** [comment]
en effet,
Très bizarre car aucun lien entre les deux messages pour moi. 0x8002 et 0x004d. 
ça le fait sur chaque appairage ou avec un capteur spécifique ?
ça le fait depuis qu'il y a eu une mise à jour du firmware ?

**Comment by tcharp38** [comment]
Je vois dans la trace un autre appairage qui se passe bien donc ca semble spécifique au device.

> [2022-04-03 17:49:34] Abeille1, Type=8002/Data indication, Status=00, ProfId=0000, ClustId=0013, SrcEP=00, DstEP=00, SrcAddrMode=02, SrcAddr=84D4, DstAddrMode=02, DstAddr=FFFD
> [2022-04-03 17:49:34]   Handled by decode004D
> [2022-04-03 17:49:34] Abeille1, Type=004d/Device announce, Addr=84D4, ExtAddr=2C1165FFFEB8A7D9, MACCapa=8E

Et le device à l 'origine est à priori un "82c167c95ed746cdbd21d6817f72c593_ORVIBO" donc https://zigbee.blakadder.com/Orvibo_CM10ZW.html
Il s'annonce tres regulierement celui la.

Depuis quand ca le fait.. aucune idée. J'ai demandé à l 'utilisateur si il avait une idée de l'evenement declencheur.

**Comment by tcharp38** [comment]
A prioi il a recu sa v2 en decembre 21 et elle etait deja en 3.21.
Donc pas de changements au niveau zigate.

**Comment by Jake309** [comment]
Salut,
Alors, j'ai tenté une réinitialisation via le menu avancé de abeille. J'ai réinclu le module (j'ai bien eu le message réannoncé -> mise a jour dans jeedom) => Rien, toujours le pb.
Il ne me reste plus que le supprimer de Jeedom et le réintégrer. Mais comme la réinitialisation change rien, j'y crois pas trop.
Sinon pour répondre à @fairecasoimeme , c'est un device que j'ai inclue il y a déjà plusieurs mois et je n'ai pas touché au firmware depuis l'achat.
 la seule chose que j'ai fais proche du début de ce bug c'est de couper et remettre sous tension le device

**Comment by Jake309** [comment]
Toujours le pb.
Ca devient poluant.
Comment puis je aider au debug ?

**Comment by tcharp38** [comment]
@Jake309 
Ca ne me plait pas mais je reflechis à inserer une verrue dans le code Abeille pour filtrer ca.

@fairecasoimeme 
Si Jake est tombé dessus, d autres pourraient y tomber à leur tour.
L'annonce déclenchée par Orvibo semble foutre la pagaille en v2. Jamais eu ca en v1.
Tu as une idée comment avancer ?

**Comment by fairecasoimeme** [comment]
Bonjour, pour moi ce problème est vraiment bizarre pour plusieurs raisons ( si j'ai bien tout compris)
- c'est le seul device à faire ce genre de chose
- la command 8002 est ok et pas la command 4D (pas trop compréhensible)
La seule solution que je vois pour comprendre le phénomène,  c'est de sniffer l'appairage.
Si vous le souhaitez, je peux faire l'analyse mais il me faut le device. Si ok, vous pouvez me contacter par mail contact[at]zigate.fr

**Comment by tcharp38** [comment]
Oui l'option du snif me semblait inevitable.
A @Jake309 de voir. Je n'ai pas cet equipement.

**Comment by Jake309** [comment]
Ca dépend combien de temps je ne l'aurai pas. Car ça gère les ouvertures voitures de la maison, donc je peux palier mais je perds le confort ^^
Je te contact demain pour ça. 
Dans le fond ça ne le dérange pas de l'envoyer pour faire avancer les choses. C'est bien le but du participatif. 
Si je c'est possible, je mettrai la zigate v1 aussi dans le paquet pour que tu puisses regarder pourquoi elle ne fonctionne plus. Si je peux la récupérer pour mon jeedom de test c'est benef.

**Comment by Jake309** [comment]
Bonjour,
Pour info, depuis que j'ai débranché le module pour te l'envoyer @fairecasoimeme , je n'ai plus de devices fantomes qui se créent.
Je sais pas si ca peut etre utile de le savoir

**Comment by fairecasoimeme** [comment]
J'ai fait les tests et sniffé : 
![device_announce](https://user-images.githubusercontent.com/22256438/164177909-8228690f-8031-42f6-8d0c-d9a0a38f26c8.JPG)
![device_announce_2](https://user-images.githubusercontent.com/22256438/164177960-47fd78a8-1cea-4476-854c-8d98488d78e6.JPG)

11:20:24.990 <- 01 80 00 00 09 5A 00 00 00 24 00 F7 00 00 00 03
11:20:26.365 <- 01 80 24 00 0D A7 01 00 00 00 00 00 00 00 00 00 00 0F 00 03
11:20:34.649 -> 01 02 10 24 02 10 02 10 24 03 
11:20:34.694 <- 01 80 00 00 09 5A 00 00 00 24 00 F7 00 00 00 03
11:20:37.016 -> 01 02 10 02 19 02 10 02 10 02 19 03 
11:20:37.072 <- 01 80 00 00 09 77 00 00 00 09 00 F7 00 00 00 03
11:20:37.125 <- 01 80 09 00 16 FA 00 00 00 00 00 00 00 00 00 00 51 8B 68 6F C4 9D 8E 58 1B 23 0F 00 03
11:20:42.771 -> 01 02 10 21 02 10 02 14 2D 02 10 02 10 02 18 02 10 03 
11:20:42.837 <- 01 80 00 00 09 5F 00 00 00 21 00 F7 00 00 00 03
11:20:44.907 -> 01 02 10 02 19 02 10 02 10 02 19 03 
11:20:44.967 <- 01 80 00 00 09 77 00 00 00 09 00 F7 00 00 00 03
11:20:45.051 <- 01 80 09 00 16 FE 00 00 00 00 00 00 00 00 00 00 51 8B 68 6F C4 9D 8E 58 1B 23 0B 00 03
11:20:48.266 -> 01 02 10 49 02 10 02 14 B0 FF FC FE 02 10 03 
11:20:48.320 <- 01 80 00 00 09 3D 00 06 00 49 02 F8 01 00 00 03
11:20:48.401 <- 01 80 12 00 0A 60 00 00 00 02 FF FC F8 01 00 00 03
11:20:53.521 <- 01 00 4D 00 0D EA 00 51 00 12 4B 00 25 1E 0E 19 8E 00 00 03
11:20:53.831 <- 01 00 4D 00 0C 95 00 51 00 12 4B 00 25 1E 0E 19 8E 7E 03
11:21:17.640 <- 01 00 4D 00 0C 6E 00 51 00 12 4B 00 25 1E 0E 19 8E 85 03

Tout semble OK avec la passerelle ZiGate.
@tcharp38 Côté Abeille, pourquoi il y a du 0x8002 pour le device announce ?

**Comment by Jake309** [comment]
Tu as fais le test avec une zigate v2 ?
J'ai dégoté un autre module pour un autre besoin. Ça permettra de faire d'autre test complémentaire.

**Comment by fairecasoimeme** [comment]
Oui testé avec une zigate+

**Comment by Jake309** [comment]
Ok, très étrange alors. 
On verra ce que donne l'autre module. 
Si ma zigate v1 refonctionne, je peux aussi faire le teste avec pour voir le comportement sans faire de changement sur jeedom et abeille. 
On voit ce que dit tcharp, mais je peux faire des test si vous êtes intéressé. 
On peut procéder par élimination.

**Comment by fairecasoimeme** [comment]
J'ai testé votre zigatev1 et chez moi elle fonctionne correctement. A mon avis, il y a un souci avec votre environnement...

**Comment by tcharp38** [comment]
@fairecasoimeme 
Abeille utilise le mode "hybride" de la Zigate.
J'en conclus que ca n'est pas le mode que tu testes ?

**Comment by fairecasoimeme** [comment]
en effet,
voici, ce que j'obtiens en mode hybride : 
13:02:00.832 -> 01 02 10 49 02 10 02 14 B0 FF FC FE 02 10 03 
13:02:00.881 <- 01 80 00 00 09 5C 00 FF 00 49 02 60 01 00 00 03
13:02:00.934 <- 01 80 12 00 0A F8 00 00 00 02 FF FC 60 01 00 00 03
13:02:20.769 <- 01 00 4D 00 0D D9 AE CC 00 12 4B 00 25 1E 0E 19 8E 00 00 03
13:02:20.871 <- 01 80 02 00 1A 1E 00 00 00 00 13 00 00 02 AE CC 02 FF FD 00 CC AE 19 0E 1E 25 00 4B 12 00 8E 6C 03
13:02:21.004 <- 01 00 4D 00 0C B4 AE CC 00 12 4B 00 25 1E 0E 19 8E 6C 03
13:02:21.111 <- 01 87 01 00 05 80 00 00 FF FC 00 03
13:02:39.345 <- 01 80 02 00 1A 10 00 00 00 00 13 00 00 02 AE CC 02 00 00 00 CC AE 19 0E 1E 25 00 4B 12 00 8E 60 03
13:02:39.637 <- 01 00 4D 00 0C 34 1A 22 04 00 53 6D 04 01 5D 6B 24 60 03
13:02:39.863 <- 01 80 12 00 0A 9A 00 00 00 02 AE CC 62 00 00 00 03
13:02:39.999 <- 01 80 11 00 08 8A 00 AE CC 00 00 13 62 00 03

**Comment by fairecasoimeme** [comment]
Apparemment, le mode hybride déconne et le 3ème device announce (et les suivant) sont faux
Je vais donc revoir le code.
Je vous tiens au courant
Fred

**Comment by fairecasoimeme** [comment]
J'ai trouvé ce qui générait l'erreur.  Ce bug peut expliquer d'autres incohérences de données dans les autres modes.
Je fix et j'essaie au plus vite de sortir un nouveau firmware avec d'autres modifs.
Fred

**Comment by Jake309** [comment]
Super ! Ça a fait avancer ton dev cette histoire. C'est cool. Ça fiabilise la zigate v2

**Comment by Jake309** [comment]
J'attends le firmware alors :p

**Comment by fairecasoimeme** [comment]
ouip. Je te renvoie ça ASAP.
Merci pour la contribution

**Comment by tcharp38** [comment]
> J'ai trouvé ce qui générait l'erreur. Ce bug peut expliquer d'autres incohérences de données dans les autres modes. Je fix et j'essaie au plus vite de sortir un nouveau firmware avec d'autres modifs. Fred

Cool que tu aies trouvé qqch.
Correctif pour v2 only ou il peut y avoir qqch pour la v1 ?

**Comment by fairecasoimeme** [comment]
fixed on v3.22

**Comment by Jake309** [comment]
Bonjour, 
On a une idée de la sortie en stable de la v3.22 pour corriger ce problème ?
Merci
