### ISSUE TITLE
IAS Enrollment

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGatev2#38]
During a Device IAS Enrollement, Zigate is responding to the IAS Zone: Zone Enroll Response with and Enroll Response code 0xe0

This is preventing the correct IAS Enrollment done by the plugin ! How can we prevent Zigate pre-empting some IAS actions ?

This is not happening on other coordinators, so it looks like Zigate specific

![Screenshot 2022-04-27 at 19 58 32](https://user-images.githubusercontent.com/8291674/165589984-8b6cf070-4a28-4333-a175-71e3b0cdee52.png)

Here after is the frame generated by the Zigate stack
![Screenshot 2022-04-27 at 19 58 58](https://user-images.githubusercontent.com/8291674/165590099-2341e6ad-e128-4dfa-abf2-b57a2b7442fa.png)

Follow by the one generated by the Plugin
![Screenshot 2022-04-27 at 19 59 40](https://user-images.githubusercontent.com/8291674/165590182-cde71616-9eec-4ce8-a529-b8e8370c28e8.png)

**Comment by fairecasoimeme** [comment]
Could you give the manufacturer code because there is specific treatment with manufacturer ocde

**Comment by pipiche38** [comment]
Could you then give the list of the manufacturer code which benefits from the special treatment

**Comment by fairecasoimeme** [comment]
There is : 
0x1002 Konke and 0x120b Heiman
The enroll response and zone_id from the trace (from zigage) correspond to nothing. I think there is a bad default enroll response when the manufacturer is unknow

**Comment by pipiche38** [comment]
I do not understand why the firmware must be aware in advance of the manufacturer that needs to be enrolled ? Especially when we are managing the all Enrollment from the UART/PLugin.

**Comment by fairecasoimeme** [comment]
fixed on future version 3.23
