### ISSUE TITLE
Zigate Node Descriptor

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGatev2#39]
When a device do a Node Descriptor Request to Zigate, it gets in return a Node Descriptor Response with the following informations

Why is the Max Incoming Transfer Size and Max Outgoing Transfer Size is set to 0 ?
This is totally different than the other CIE. Does that mean teh CIE tell the Routers and Devices its have unlimited Incoming/Outgoing transfer size ?

What is the Purpose of the Network Manager flag ? This also doesn't look common in other gateways 

<img width="592" alt="Screenshot 2022-04-28 at 09 56 15" src="https://user-images.githubusercontent.com/8291674/165705105-48a95fe9-ddb2-449e-91b0-c6e5437b2cce.png">

**Comment by fairecasoimeme** [comment]
I don't know, I will investigate

**Comment by fairecasoimeme** [comment]
Ok we can find the information in the ZPSCFG

![image](https://user-images.githubusercontent.com/22256438/165708961-8795c40b-f136-4d5d-a5f4-97b818aa01cb.png)

**Comment by pipiche38** [comment]
yep. but why 0 for Max Incoming and Max outgoing tranfsert size ? Does that mean unlimited ?

**Comment by fairecasoimeme** [comment]
This is the default value from nxp application note. Apparently, this value is not editable now.
Here is the doc from JN-UG-3113: 
![image](https://user-images.githubusercontent.com/22256438/165727946-021347ce-85b8-4197-9d35-290763400d80.png)

**Comment by pipiche38** [comment]
So then I'm really questioning why 0. this doesn't make sense

**Comment by fairecasoimeme** [comment]
I don't know what is the  consequence for devices. But if you want to test with other value, tell me how much what you need and I do.

**Comment by pipiche38** [comment]
My question was not about testing, it was much more questioning why 0 and what is the meaning, when I see all other coordinators/firmware coming with different values but definitively different than 0.

Looks like here this is not set accordingly to the documentation

**Comment by fairecasoimeme** [comment]
As I already said, the value 0, according to nxp documentation, for coordinator is not editable. 0 mean not avalaible or rather "calculated"
But, besides other coordinators give different values, what is the purpose ? what is nor working properly with devices ?

> Looks like here this is not set accordingly to the documentation

Which documentation are you talking about ?

**Comment by fairecasoimeme** [comment]
I simply follow the NXP documentation and it's clear for this point. 
The maximum Incoming and outgoing Transfer size properties from node descriptor is used to give informations to devices. There is no link with PDM or any data corruptions and there is no data corruption on zigate v2 against zigate v1. The only problem is PDM tables which are full in under some conditions (that is difficult to reproduce)

The firmware is open, you can download/compile and do test.

Thanks for all
