### ISSUE TITLE
ZiGate not handling correctly IAS ACE messages

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGatev2#48]
Here attached a pairing followed by some action on an IAS remote.
None of the IAS ACE command are sent to UART

[IAS-message.pcapng.zip](https://github.com/fairecasoimeme/ZiGatev2/files/9488025/IAS-message.pcapng.zip)

**Comment by fairecasoimeme** [comment]
I'll see ASAP.
