### ISSUE TITLE
FW 0005-03A0: Unexpected 'Management LQI response' or 'Routing table response' messages

### ISSUE THREAD

**Issue by tcharp38** [fairecasoimeme/ZiGatev2#59]
Not really clear what is triggering this type of messages but with FW 0005-03A0, I can see some unexpected responses messages that are not requested by plugin.

- Management LQI response
- Routing table response

Message source is not always the same device.
Zigate in HYBRID mode.

No other informations so far so just as informative.
Corresponding Abeille issue: https://github.com/KiwiHC16/Abeille/issues/2546

**Comment by fairecasoimeme** [comment]
Hi,
It's normal, ZiGate generate LQI and Route request periodically to enhance the responsivity. ZiGate ask the routers on the network to give its routes and neighbours. With this mechanism, the routing seems to be more efficient.
This update is notified here : https://github.com/fairecasoimeme/ZiGatev2#changelog

Normally, this update don't change the other treatment

**Comment by tcharp38** [comment]
Ok thanks.
I did not understood the changelog.
