### ISSUE TITLE
Unable to make ZiGate member of a group

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/ZiGatev2#9]
There is no way to get zigate as part of a group membership!

> May 08 15:48:34 rasp domoticz[11801]: 2021-05-08 15:48:34.618  ZiGate-V2: (ZiGate-V2) _sendData to ZiGate NOW  - [10] 0060 02000001010000
> May 08 15:48:34 rasp domoticz[11801]: 2021-05-08 15:48:34.669  ZiGate-V2: (ZiGate-V2) ZigateRead - MsgType: 8000, MsgLength: 0009, MsgCRC: c2, Data: 00000060002b0000, LQI: 0
> May 08 15:48:34 rasp domoticz[11801]: 2021-05-08 15:48:34.669  ZiGate-V2: (ZiGate-V2) Decod8000 Received         [  ] PacketType:  0060 TypeSqn: 00 sqn_app: 00/0 sqn_aps: 2b/43 Status: [00] npdu: 00 apdu: 00
> May 08 15:48:34 rasp domoticz[11801]: 2021-05-08 15:48:34.670  ZiGate-V2: (ZiGate-V2) statusOnGrpCommand - Status: 00 for Command: 0060

But no 8060 received !

**Comment by fairecasoimeme** [comment]
The treatment of groups on 0x0000 address is different from the zigate v1.

Normally, I fixed the issue to get 0x8060 and 0x8062 command
